[package]
name = "atomcad"
version = "0.1.0"
authors = [
    "Mark Friedenbach <mark@friedenbach.org>",
    "Lachlan Sneff <lachlan.sneff@gmail.com>",
]
license = "MPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/render",
    "crates/periodic-table",
    "crates/common",
    "crates/scene",
]

[workspace.dependencies]
render = { package = "atomcad-render", path = "crates/render" }
common = { package = "atomcad-common", path = "crates/common" }
periodic-table = { package = "atomcad-periodic-table", path = "crates/periodic-table" }
scene = { package = "atomcad-scene", path = "crates/scene" }
ultraviolet = { version = "0.9.1", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
petgraph = { version = "0.6.3", features = ["serde-1"] }


[dependencies]
render = { workspace = true }
common = { workspace = true }
periodic-table = { workspace = true }
scene = { workspace = true }
ultraviolet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = "0.3.28"
log = "0.4.19"
nom = "7.1.3"
winit = { git = "https://github.com/rust-windowing/winit", rev = "924f3323b56190ef93829af080fcca046c19bc80", features = [
    "android-native-activity",
] }
env_logger = "0.10.0"

# android:
[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.4", features = ["native-activity"] }
android_logger = "0.13.1"

# Windows
[target.'cfg(target_os = "windows")'.dependencies]
muda = "0.9.1"
windows-sys = { version = "0.48", features = ["Win32_UI_WindowsAndMessaging"] }

# macOS:
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3.64"
wasm-bindgen-futures = "0.4.37"
console_error_panic_hook = "0.1.7"
console_log = "1"
